/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author USER
 */
public class MainWindow extends javax.swing.JFrame {
    
    private model.LibraryDatabase database = new model.LibraryDatabase();
    private String currentSortColumn = "";
    private boolean ascending = true;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
public MainWindow() {
    initComponents();
        
    addItemButton.setToolTipText("Add a new library item");
    deleteItemButton.setToolTipText("Delete the selected item");
    undoDeleteButton.setToolTipText("Undo deletion of the library items");
    borrowButton.setToolTipText("Borrow the selected library item");
    returnButton.setToolTipText("Return a borrowed item");
    searchButton.setToolTipText("Search items by title");
    sortButton.setToolTipText("Sort the library items");

    database.getItems().addAll(
        utils.FileHandler.loadItems("library_data.txt")
    );
    
    itemsTable.setDefaultRenderer(
            Object.class,
            new OverdueTableRenderer(database)
    );

    refreshTable();
}
    
    private void updateTableHeaders() {

    javax.swing.table.TableColumnModel columnModel = itemsTable.getColumnModel();

    for (int i = 0; i < columnModel.getColumnCount(); i++) {

        String columnName = columnModel.getColumn(i).getHeaderValue().toString();

        // Remove old arrows
        columnName = columnName.replace(" ▲", "").replace(" ▼", "");

        if (columnName.equals(currentSortColumn)) {

            columnName += ascending ? " ▲" : " ▼";
        }

        columnModel.getColumn(i).setHeaderValue(columnName);
    }

    itemsTable.getTableHeader().repaint();
}

    private void refreshTable() {

    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) itemsTable.getModel();

    model.setRowCount(0);

    for (model.LibraryItem item : database.getItems()) {

        String type = item.getClass().getSimpleName();

        String status;

        if (item.isBorrowed()) {

    if (item.getBorrowDate() != null) {

        long daysBorrowed =
            java.time.temporal.ChronoUnit.DAYS.between(
                item.getBorrowDate(),
                java.time.LocalDate.now());

        if (daysBorrowed > 14) {

            status = "Overdue (" + (daysBorrowed - 14) + " days)";

        } else if (item.getReservationQueueSize() > 0) {

            status = "Borrowed (" + item.getReservationQueueSize() + " waiting)";

        } else {

            status = "Borrowed";

        }

    } else {

        status = "Borrowed";

    }

} else {

    status = "Available";

}

        model.addRow(new Object[]{
            item.getId(),
            item.getTitle(),
            item.getAuthor(),
            item.getYear(),
            type,
            status
        });

    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        borrowButton = new javax.swing.JButton();
        returnButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        userIdField = new javax.swing.JTextField();
        itemIdField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        authorField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        yearField = new javax.swing.JTextField();
        typeComboBox = new javax.swing.JComboBox<>();
        addItemButton = new javax.swing.JButton();
        deleteItemButton = new javax.swing.JButton();
        undoDeleteButton = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        categoryReportButton = new javax.swing.JButton();
        borrowReportButton = new javax.swing.JButton();
        overdueReportButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        searchAlgorithmCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        sortAlgorithmCombo = new javax.swing.JComboBox<>();
        sortButton = new javax.swing.JButton();
        sortByComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SMART LIBRARY CIRCULATION SYSTEM");

        jTabbedPane1.setToolTipText("");

        itemsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Author", "Year", "Type", "Borrowed"
            }
        ));
        jScrollPane2.setViewportView(itemsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Items", jPanel1);

        jLabel1.setText("User ID:");

        borrowButton.setText("Borrow Item");
        borrowButton.addActionListener(this::borrowButtonActionPerformed);

        returnButton.setText("Return Item");
        returnButton.addActionListener(this::returnButtonActionPerformed);

        jLabel3.setText("Item ID:");

        userIdField.addActionListener(this::userIdFieldActionPerformed);

        itemIdField.addActionListener(this::itemIdFieldActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(itemIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(borrowButton)
                        .addGap(60, 60, 60)
                        .addComponent(returnButton)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(itemIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowButton)
                    .addComponent(returnButton))
                .addContainerGap(278, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Borrow/Return", jPanel2);

        jLabel2.setText("Title");

        jLabel4.setText("Author");

        jLabel5.setText("Type");

        jLabel6.setText("Year");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book", "Magazine", "Journal" }));

        addItemButton.setText("Add Item");
        addItemButton.addActionListener(this::addItemButtonActionPerformed);

        deleteItemButton.setText("Delete Item");
        deleteItemButton.addActionListener(this::deleteItemButtonActionPerformed);

        undoDeleteButton.setText("Undo Delete");
        undoDeleteButton.addActionListener(this::undoDeleteButtonActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(titleField)
                        .addComponent(authorField)
                        .addComponent(yearField, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE))
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(328, Short.MAX_VALUE)
                .addComponent(addItemButton)
                .addGap(18, 18, 18)
                .addComponent(deleteItemButton)
                .addGap(18, 18, 18)
                .addComponent(undoDeleteButton)
                .addGap(275, 275, 275))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addItemButton)
                    .addComponent(deleteItemButton)
                    .addComponent(undoDeleteButton))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel3);

        categoryReportButton.setText("Category Distribution");
        categoryReportButton.addActionListener(this::categoryReportButtonActionPerformed);

        borrowReportButton.setText("Most Borrowed Items");
        borrowReportButton.addActionListener(this::borrowReportButtonActionPerformed);

        overdueReportButton.setText("Overdue Users");
        overdueReportButton.addActionListener(this::overdueReportButtonActionPerformed);

        jLabel7.setText("Reports");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(borrowReportButton)
                    .addComponent(overdueReportButton)
                    .addComponent(categoryReportButton))
                .addContainerGap(655, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(categoryReportButton)
                .addGap(18, 18, 18)
                .addComponent(borrowReportButton)
                .addGap(18, 18, 18)
                .addComponent(overdueReportButton)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Report", jPanel6);

        jLabel8.setText("Title");

        searchButton.setText("Search");
        searchButton.addActionListener(this::searchButtonActionPerformed);

        jLabel9.setText("Search Algorithm");

        searchAlgorithmCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Linear Search", "Binary Search", "Recursive Search" }));

        jLabel10.setText("Sort Algorithm");

        sortAlgorithmCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selection Sort", "Merge Sort" }));

        sortButton.setText("Sort Items");
        sortButton.addActionListener(this::sortButtonActionPerformed);

        sortByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Title", "Author", "Year" }));
        sortByComboBox.addActionListener(this::sortByComboBoxActionPerformed);

        jLabel11.setText("Sort By");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(sortAlgorithmCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))
                        .addComponent(sortButton)
                        .addGap(68, 68, 68))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchAlgorithmCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchButton)))
                .addGap(512, 512, 512))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchAlgorithmCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addGap(56, 56, 56)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortAlgorithmCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sortButton))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search & Sort", jPanel4);

        jLabel12.setBackground(java.awt.Color.lightGray);
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("The Real Coconut Smart Library Circulation System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIdFieldActionPerformed

    private void itemIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdFieldActionPerformed

    private void addItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemButtonActionPerformed
        // TODO add your handling code here:
        String title = titleField.getText();
        String author = authorField.getText();
        String yearText = yearField.getText();

        // Validation
        if (title.isEmpty() || author.isEmpty() || yearText.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Please fill all fields!");

            return;
        }

        int year;

        try {
            year = Integer.parseInt(yearText);
        } catch (NumberFormatException e) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Year must be a number!");

            return;
        }

        String type = typeComboBox.getSelectedItem().toString();
        String id = utils.IDGenerator.generateId();

        model.LibraryItem item;

        if (type.equals("Book")) {
            item = new model.Book(id, title, author, year, "ISBN");
        } else if (type.equals("Magazine")) {
            item = new model.Magazine(id, title, author, year);
        } else {
            item = new model.Journal(id, title, author, year);
        }

        database.addItem(item);

        utils.FileHandler.saveItems(database.getItems(), "library_data.txt");

        refreshTable();

    }//GEN-LAST:event_addItemButtonActionPerformed

    private void borrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowButtonActionPerformed
        // TODO add your handling code here:
    String itemId = itemIdField.getText();
    String userId = userIdField.getText();

    if (itemId.isEmpty() || userId.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Enter both User ID and Item ID.");
        return;
    }

    for (model.LibraryItem item : database.getItems()) {

        if (item.getId().equals(itemId)) {

            // 🔴 Case 1: Same user trying to borrow again
            if (item.isBorrowed() && item.getBorrowedBy() != null && 
                    userId.equalsIgnoreCase(item.getBorrowedBy())) {

                javax.swing.JOptionPane.showMessageDialog(this,
                        "You already borrowed this item.");

                return;
            }

            // 🔴 Case 2: Another user tries to borrow
            if (item.isBorrowed() && item.getBorrowedBy() != null &&
                    !userId.equalsIgnoreCase(item.getBorrowedBy())) {

                javax.swing.JOptionPane.showMessageDialog(this,
                        "Item already borrowed by " + item.getBorrowedBy());

                // Optional: add to reservation queue
                model.UserAccount user = new model.UserAccount(userId, "User");
                item.addToReservation(user);

                javax.swing.JOptionPane.showMessageDialog(this,
                        "You have been added to the reservation queue.\nPosition: "
                        + item.getReservationQueueSize());

                return;
            }

            // 🟢 Case 3: Item is available
            item.setBorrowed(true);
            item.setBorrowedBy(userId);
            item.setBorrowDate(java.time.LocalDate.now());
            item.borrowCount++;

            javax.swing.JOptionPane.showMessageDialog(this,
                    "\"" + item.getTitle() + "\" borrowed successfully.");

            utils.FileHandler.saveItems(database.getItems(), "library_data.txt");

            refreshTable();
            return;
        }
    }

    javax.swing.JOptionPane.showMessageDialog(this,
            "Item not found.");
    }//GEN-LAST:event_borrowButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        String itemId = itemIdField.getText();

        if (itemId.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Enter Item ID to return.");
            return;
        }

    boolean found = false;

    for (model.LibraryItem item : database.getItems()) {

        if (item.getId().equals(itemId)) {

            found = true;

            if (!item.isBorrowed()) {

                javax.swing.JOptionPane.showMessageDialog(this,
                        "This item is already available.");

            } else {

                model.UserAccount nextUser = item.getNextReservation();

                if (nextUser != null) {

                    // Assign book to next user automatically
                    item.setBorrowed(true);
                    item.setBorrowedBy(nextUser.getUserId());
                    item.setBorrowDate(java.time.LocalDate.now());
                    item.borrowCount++;

                    javax.swing.JOptionPane.showMessageDialog(this,
                            "Book returned.\nAutomatically borrowed by next user in queue:\n"
                            + nextUser.getUserId());

                } else {

                    // No reservations waiting
                    item.setBorrowed(false);
                    item.setBorrowedBy(null);
                    item.setBorrowDate(null);

                    javax.swing.JOptionPane.showMessageDialog(this,
                            "\"" + item.getTitle() + "\" has been returned.");

                }

                utils.FileHandler.saveItems(database.getItems(), "library_data.txt");

            }

            break;

        }

    }

    if (!found) {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Item not found.");

    }

    refreshTable();
    
    }//GEN-LAST:event_returnButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String title = searchField.getText();
    String algorithm = searchAlgorithmCombo.getSelectedItem().toString();

    model.LibraryItem result = null;

    if (algorithm.equals("Linear Search")) {

        result = controller.SearchEngine.linearSearchByTitle(database.getItems(), title);

    } else if (algorithm.equals("Binary Search")) {

        controller.SearchEngine.selectionSortByTitle(database.getItems());
        result = controller.SearchEngine.binarySearchByTitle(database.getItems(), title);

    } else {

        result = controller.SearchEngine.recursiveSearchByTitle(database.getItems(), title, 0);

    }

    if (result != null) {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Item Found:\nTitle: " + result.getTitle()
                + "\nAuthor: " + result.getAuthor());

    } else {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Item not found.");

    }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void sortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortButtonActionPerformed
        // TODO add your handling code here:
      String sortBy = sortByComboBox.getSelectedItem().toString();
    String algorithm = sortAlgorithmCombo.getSelectedItem().toString();
    
    // Toggle direction if same column
    
    if (sortBy.equals(currentSortColumn)) {
        ascending = !ascending;
    } else {
        ascending = true;
        currentSortColumn = sortBy;
    }

    if (algorithm.equals("Selection Sort")) {

        if (sortBy.equals("Title")) {
            controller.SearchEngine.selectionSortByTitle(database.getItems());

        } else if (sortBy.equals("Author")) {
            controller.SearchEngine.selectionSortByAuthor(database.getItems());

        } else if (sortBy.equals("Year")) {
            controller.SearchEngine.selectionSortByYear(database.getItems());
        }

    } else if (algorithm.equals("Merge Sort")) {

        if (sortBy.equals("Title")) {
            controller.SearchEngine.mergeSortByTitle(database.getItems());

        } else if (sortBy.equals("Author")) {
            controller.SearchEngine.mergeSortByAuthor(database.getItems());

        } else if (sortBy.equals("Year")) {
            controller.SearchEngine.mergeSortByYear(database.getItems());

        } 
        // Optional: add mergeSortByYear too
    }
    
    if (!ascending) {
        java.util.Collections.reverse(database.getItems());
    }

    updateTableHeaders();
    refreshTable();
    }//GEN-LAST:event_sortButtonActionPerformed

    private void deleteItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemButtonActionPerformed
        // TODO add your handling code here:
         String title = titleField.getText();

    if (title.isEmpty()) {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Enter the book title to delete!");

        return;

    }

    boolean found = false;

    for (model.LibraryItem item : database.getItems()) {

        if (item.getTitle().equalsIgnoreCase(title)) {

            found = true;

            // Prevent deletion if borrowed
            if (item.isBorrowed()) {

                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cannot delete \"" + item.getTitle() + "\" because it is currently borrowed.");

                return;

            }

            database.removeItem(item.getId());

            javax.swing.JOptionPane.showMessageDialog(this,
                    "\"" + item.getTitle() + "\" has been deleted.");

            utils.FileHandler.saveItems(database.getItems(), "library_data.txt");

            refreshTable();

            return;

        }

    }

    if (!found) {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Book not found.");

    }
    }//GEN-LAST:event_deleteItemButtonActionPerformed

    private void undoDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoDeleteButtonActionPerformed
        // TODO add your handling code here:
        model.LibraryItem restoredItem = database.undoDelete();

    if (restoredItem != null) {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Deletion undone.\n\n\""
                + restoredItem.getTitle()
                + "\" has been restored.");

        utils.FileHandler.saveItems(database.getItems(), "library_data.txt");

    } else {

        javax.swing.JOptionPane.showMessageDialog(this,
                "Nothing to undo.");

    }

    refreshTable();
    }//GEN-LAST:event_undoDeleteButtonActionPerformed

    private void categoryReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryReportButtonActionPerformed
        // TODO add your handling code here:
        String report = controller.ReportGenerator.categoryDistribution(database.getItems());

        javax.swing.JOptionPane.showMessageDialog(this, report);
    }//GEN-LAST:event_categoryReportButtonActionPerformed

    private void borrowReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowReportButtonActionPerformed
        // TODO add your handling code here:
        String report = controller.ReportGenerator.mostBorrowedItems(database.getItems());

        javax.swing.JOptionPane.showMessageDialog(this, report);
    }//GEN-LAST:event_borrowReportButtonActionPerformed

    private void overdueReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overdueReportButtonActionPerformed
        // TODO add your handling code here:
        String report = controller.ReportGenerator.overdueUsers(database.getItems());

        javax.swing.JOptionPane.showMessageDialog(this, report);
    }//GEN-LAST:event_overdueReportButtonActionPerformed

    private void sortByComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortByComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemButton;
    private javax.swing.JTextField authorField;
    private javax.swing.JButton borrowButton;
    private javax.swing.JButton borrowReportButton;
    private javax.swing.JButton categoryReportButton;
    private javax.swing.JButton deleteItemButton;
    private javax.swing.JTextField itemIdField;
    private javax.swing.JTable itemsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton overdueReportButton;
    private javax.swing.JButton returnButton;
    private javax.swing.JComboBox<String> searchAlgorithmCombo;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> sortAlgorithmCombo;
    private javax.swing.JButton sortButton;
    private javax.swing.JComboBox<String> sortByComboBox;
    private javax.swing.JTextField titleField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JButton undoDeleteButton;
    private javax.swing.JTextField userIdField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
